/*global module:false*/
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    meta: {
      version: '0.1.0',
      banner: '/*! Tribe Social - v<%= meta.version %> - ' +
        '<%= grunt.template.today("yyyy-mm-dd") %>\n' +
        '* THIS FILE IS GENERATED BY GRUNT. DO NOT MODIFY MANUALLY\n' +
        '* http://tribesocial.com/\n' +
        '* Copyright (c) <%= grunt.template.today("yyyy") %> ' +
        'campJS.com; */'
    },
    lint: {
      files: []//'grunt.js', 'src/app.js', 'src/models/*.js', 'src/collections/*.js', 'src/views/*.js', 'src/router.js', 'spec/**/*.js', 'src/statechart.js']
    },
    concat: {
      libs: {
        src: ['<banner:meta.banner>',
              'src/vendor/jquery.js',
              'src/vendor/backbone.js',
              'src/vendor/bootstrap.js',
              'src/vendor/prelude.js',
              'src/vendor/handlebars.runtime.js',
              'src/vendor/jquery-form.js',
        ],
        dest: 'public/js/libs.js'
      },
      campjs: {
        src: ['<banner:meta.banner>',
             'src/campjs.js',
             'src/models/*.js',
             'src/collections/*.js',
             'src/views/*.js',
             'src/router.js'],
        dest: 'public/js/campjs.js'
      },
      css: {
        src: ['<banner:meta.banner>',
              'vendor/css/bootstrap.css',
              'vendor/css/bootstrap.responsive.css',
              'public/css/style.stylus.css'
        ],
        dest: 'public/css/screen.css'
      }
    },
    min: {
      libs: {
        src: ['<banner:meta.banner>', 'public/js/libs.js'],
        dest: 'public/js/libs.min.js'
      },
      campjs: {
        src: ['<banner:meta.banner>', 'public/js/campjs.js'],
        dest: 'public/js/campjs.min.js'
      },
      templates: {
        src: ['<banner:meta.banner>', 'public/js/templates.js'],
        dest: 'public/js/templates.min.js'
      }
    },
    recess: {
      css: {
        src: ['public/css/screen.css'],
        dest: 'public/css/screen.min.css',
        options: {
          compress: true,
          noIDs: false
        }
      }
    },
    handlebars: {
      all: {
        src: 'public/templates/*.handlebars',
        dest: 'public/js/templates.js'
      }
    },
    jade: {
      all: {
        src: 'src/templates/*.jade',
        dest: 'public/templates/',
        options: {
          client: false
        }
      },
      layout: {
        src: 'src/index.jade',
        dest: 'public/',
        options: {
          client: false
        }
      }
    },
    watch: {
      files: ['<config:lint.files>', 'src/**', 'vendor/**'],
      tasks: 'jade handlebars shell:stylus shell:rename concat min recess'
    },
    shell: {
      stylus: {
        command: './node_modules/.bin/stylus --use nib ./src/css/*.stylus -o ./public/css/'
      },
      clean: {
        command: 'rm public/templates/*.handlebars'
      },
      rename: {
        command: 'for file in ./public/templates/*.html\n\
          do \n\
          mv ${file} ${file/.html/.handlebars} \n\
          done'
      }
    }
  });

  grunt.loadNpmTasks('grunt-handlebars');
  grunt.loadNpmTasks('grunt-recess');
  grunt.loadNpmTasks('grunt-jade');
  grunt.loadNpmTasks('grunt-coffee');
  grunt.loadNpmTasks('grunt-shell');

  // Default task.
  grunt.registerTask('default', 'jade shell:clean handlebars shell:stylus shell:rename concat min recess');

};
